model:
  type: "gpt2"
  name: "gpt2-medium"
  # type: "llama"
  # name: "microsoft/Phi-3-mini-4k-instruct"
  models_dir: "../../../models"
  device: "cpu"
  save_to_local: True

logging:
  log_level: "INFO"

generation:
  prompt: "The Eiffel Tower is in"
  # prompt: "The Space Needle is in downtown"
  corrupted_layer_idx: 7
  corrupted_token_idx: [0, 1, 2]
  max_new_tokens: 1
  corrupted_block_idx: 0
  noise_multiplier: 9