# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

defaults:
  - /model_base@_global_.model: default
  - /model@_global_.model: gpt2-large
  - /generation@_global_.generation: generation
  - /dataset_facts@_global_.dataset_facts: counterfact
  - /dataset_sm@_global_.dataset_sm: wikitext
  - /tracing@_global_.tracing: aquin
  - _self_

name: rome-layer-sweep
