handler: "gpt2"
name: "gpt2-medium"
models_dir: "./models"
device: "cuda"
save_to_local: True # Keep this True until you specifically do not want the model cached locally
layer_name_template: "transformer.h.{}.mlp.c_proj"
layer: 8