# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

num_of_runs: 100000
filename: "causal_trace_{}"
batch_size: 100
k_N: 50
v_N: 50
prefix_range: [2, 10]
num_trace_runs: 10