"""
common.py
===============

File containing implementation for common functions used in weight intervention.

:copyright: 2025 Jakub Res
:license: MIT
:author: Jakub Res <iresj@fit.vut.cz>
"""

from pathlib import Path
import torch
from typing import Tuple, List
from src.handlers.rome import ModelHandler
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm
from enum import Enum
import numpy as np


import logging
LOGGER = logging.getLogger(__name__)

writer = SummaryWriter()

def generate_prefixes(
        handler: ModelHandler,
        N: int,
        prefix_range: Tuple[int, int] = (2, 11),
        additional_prompts: List[str] = []
    ) -> List[str]:
    """
    Generates template prefixes using the model.
    
    :param handler: Description
    :type handler: ModelHandler
    :param subject: Description
    :type subject: str
    :param N: Description
    :type N: int
    :param prefix_range: Description
    :type prefix_range: Tuple[int, int]
    :param additional_prompts: Description
    :type additional_prompts: List[str]
    :return: Templates of random prefixes with a placeholder for subject, generated by the model, and additional prompts provided by the user.
    :rtype: List[str]
    """

    if N > 0:
        prompts = handler.tokenize_prompt([handler.tokenizer.eos_token] * (N-1))
        with torch.no_grad():
            outputs = handler.model.generate(**prompts, max_length=prefix_range[1], do_sample=True)
        templates = ["{}"] + handler.tokenizer.batch_decode(outputs[:,1:])
    else:
        templates = []

    for i in range(len(templates)):
        templates[i] = templates[i].replace("{", "").replace("}", "") # Remove the curly brackets from the generated templates to avoid confusion with the placeholder
        templates[i] = templates[i] + ".{}"

    templates += additional_prompts

    return templates

def gather_k(
        handler: ModelHandler, 
        fact_tuple: Tuple[str, str, str], 
        N: int = 50, 
        prefix_range: Tuple[int, int] = (2, 11),
        additional_prompts = []
    ) -> torch.Tensor | None:
    templates = generate_prefixes(handler, N, prefix_range, additional_prompts=additional_prompts)
    for i in range(len(templates)):
        templates[i] = templates[i].format(fact_tuple[1])
    prompts = handler.tokenize_prompt(templates)

    N += len(additional_prompts)

    index = (prompts.attention_mask[torch.arange(N)].sum(dim=1)) - 1
    # TODO: Add support for dynamic batch size
    k = None
    def k_hook(_, input):
        nonlocal k
        k = input[0][:,index].mean(dim=[0,1])
        return input

    handler.set_k_hook(k_hook)
    handler.model(**prompts)
    handler.remove_hooks()

    return handler.device_manager.safe_to_device(k)

def get_subject_position(handler, prompt, subject):
    """
    TODO
    Get position of subject in prompt
    """
    input_ids_prompt = handler.tokenize_prompt(prompt)["input_ids"]
    input_ids_subject = handler.tokenize_prompt(subject)["input_ids"]
    windows = input_ids_prompt.unfold(1, input_ids_subject.size(1), 1)
    matches = (windows == input_ids_subject).all(dim=2)
    subject_position = list(set(matches.nonzero(as_tuple=True)[1].tolist()))

    if len(subject_position) == 0:
        # The tokenizer most likely learned specific tokens with space as prefix (" Rome" instead of " " + "Rome")
        input_ids_subject = handler.tokenize_prompt(f" {subject}")["input_ids"]
        windows = input_ids_prompt.unfold(1, input_ids_subject.size(1), 1)
        matches = (windows == input_ids_subject).all(dim=2)
        subject_position = list(set(matches.nonzero(as_tuple=True)[1].tolist()))

    if len(subject_position) == 0:
        LOGGER.error(f"{subject_position}\t{prompt}\t{input_ids_subject}\t{input_ids_prompt}")
        return -1
        # raise Exception("Subject not found during the prompt preprocess. Mostly due to tokenization issues.")

    subject_position[0] += input_ids_subject.size(1) - 1
    return subject_position[0]

def get_subject_index(handler, prompts, fact_tuple, subject_understanding_template) -> torch.Tensor | None:
    new_target_ids = handler.tokenize_prompt(fact_tuple[2])["input_ids"][0]
    last_subject_index = (prompts.attention_mask[torch.arange(prompts.input_ids.shape[0])].sum(dim=1))

    fact_prompt = handler.tokenize_prompt(fact_tuple[0].format(fact_tuple[1]))
    u_fact_prompt = handler.tokenize_prompt(subject_understanding_template.format(fact_tuple[1]))


    # Last subject token index computation
    pos = get_subject_position(handler, fact_tuple[0].format(fact_tuple[1]), fact_tuple[1])
    if pos == -1:
        return None

    subject_reverse_pos = len(fact_prompt["input_ids"][0]) - pos
    last_subject_index[:prompts.input_ids.shape[0]-1] -= subject_reverse_pos + len(new_target_ids) - 1


    # Last subject token index computation for understanding prompt
    pos = get_subject_position(handler, subject_understanding_template.format(fact_tuple[1]), fact_tuple[1])
    if pos == -1:
        return None
    
    u_sub_reverse_pos = len(u_fact_prompt["input_ids"][0]) - pos
    last_subject_index[-1] -= u_sub_reverse_pos

    return last_subject_index

def optimize_v(
        handler: ModelHandler,
        fact_tuple: Tuple[str, str, str, str],
        N_prompts: int,
        N_optim_steps: int,
        subject_understanding_template: str = "{} is a",
        verbose: bool = True
    ) -> Tuple[torch.Tensor, torch.Tensor] | None:
    # Initialization
    v_init = None
    dkl_orig = None

    # Prompt preparation
    new_target_ids = handler.tokenize_prompt(fact_tuple[2])["input_ids"][0]

    templates = generate_prefixes(handler, N_prompts, additional_prompts=[subject_understanding_template])
    LOGGER.info(f"Templates for v-step: {templates}")
    for i in range(len(templates)):
        templates[i] = templates[i].format(fact_tuple[0].format(fact_tuple[1]))

    if new_target_ids.size(0) > 1:
        templates = [template + handler.tokenizer.decode(new_target_ids[:-1]) for template in templates]
    
    prompts = handler.tokenize_prompt(templates)

    last_subject_index = get_subject_index(handler, prompts, fact_tuple, subject_understanding_template)
    if last_subject_index is None:
        LOGGER.error("Subject index computation failed during v computation.")
        return None

    # The optimizer setup
    # Create delta on CPU first, then move through device_manager for tracking
    delta = torch.zeros((handler.emb_shape), requires_grad=False, dtype=handler.dtype)
    delta = handler.device_manager.safe_to_device(delta).requires_grad_(True)

    opt = torch.optim.Adam([delta], lr=handler.lr)

    def delta_hook(module, _, output):
        nonlocal v_init
        if module == handler._get_module(handler._layer_name_template.format(handler._layer)):
            new_output = output.clone()
            if v_init == None:
                v_init = output[0,last_subject_index[0]].detach().clone()
            for i, idx in enumerate(last_subject_index):
                new_output[i,idx,:] = new_output[i,idx,:] + delta.to(output.dtype)
        return new_output


    # Create index for all the prompts and targets
    index_positions = []
    for i in range(N_prompts):
        index_positions.append(torch.arange((prompts.attention_mask[i].sum()) - len(new_target_ids), (prompts.attention_mask[i].sum())).tolist())
    
    index_ids = new_target_ids.repeat(N_prompts, 1)
    dkl_index = (prompts.attention_mask[N_prompts:].sum(dim=0)) - 1

    for i in range(N_optim_steps):
        opt.zero_grad()
        handler.device_manager.clear_cache()

        handler.set_delta_hook(delta_hook)
        outputs = handler.model(**prompts)
        handler.remove_hooks()

        log_probs = torch.log_softmax(outputs.logits, dim=2)[torch.arange(N_prompts).unsqueeze(1),index_positions,index_ids].squeeze(0)

        st = torch.stack([outputs.logits[-1,dkl_index,:]], dim=0)
        
        dkl_log_probs = torch.nn.functional.log_softmax(st, dim=1)

        if dkl_orig == None:
            dkl_orig = dkl_log_probs.detach().clone() # Reusing this accross multiple epochs

        dkl = handler.kl_factor * torch.nn.functional.kl_div(dkl_orig, dkl_log_probs, log_target=True, reduction="batchmean")
        weight_decay = handler.weight_decay * (torch.norm(delta) / (torch.norm(v_init) ** 2))
        
        pred_loss = (-1 * log_probs).mean()
        loss = pred_loss + dkl + weight_decay

        if verbose:
            LOGGER.info(f"Epoch {i} log_probs {pred_loss} dkl {dkl} wd {weight_decay}")

        if i == N_optim_steps - 1:
            break
        
        loss.backward()
        opt.step()

        max_norm = 4 * v_init.norm()
        if delta.norm() > max_norm:
            with torch.no_grad():
                delta[...] = delta * max_norm / delta.norm()

    return delta

def insert_kv(handler: ModelHandler, k: torch.Tensor, delta: torch.Tensor) -> None:
    old_W = handler._get_module(handler._layer_name_template.format(handler._layer)).weight.clone() # extract from the model

    # Fix the transposed models
    old_W_transposed = False
    if old_W.shape[0] != k.shape[0]:
        old_W = torch.transpose(old_W,0,1)
        old_W_transposed = True

    inv_cov = get_second_moment(handler).to(handler.dtype)
    left = inv_cov @ k.unsqueeze(1)
    left = left.squeeze()
    left = left / left.norm()
    right = delta / torch.dot(k, left)


    LOGGER.info(f"Delta norm: {delta.norm().item()}")
    LOGGER.info(f"Division Factor: {torch.dot(k, left).item()}")
    LOGGER.info(f"Right vector norm: {right.norm()}")

    update_matrix = left.unsqueeze(1) @ right.unsqueeze(0)
    try:
        new_W = old_W + update_matrix
    except:
        new_W = old_W + update_matrix.T
    if old_W_transposed:
        new_W = torch.transpose(new_W,0,1)

    # Insert new weights back to the model
    handler._get_module(handler._layer_name_template.format(handler._layer)).weight = torch.nn.Parameter(new_W)
    return new_W.to(handler.dtype), old_W  # Cast to model dtype

class SM_Method(Enum):
    RANDOM = 1
    WIKIPEDIA = 2

def second_moment_wikipedia(handler, N_rounds, N_k):
    """
    Compute inverse covariance C^-1 where C = E[k @ k^T] using Wikipedia data.
    
    Math:
        C = (1/N) * sum_i(k_i^T @ k_i)  where k_i are layer inputs
        Returns C^-1 (needed for ROME weight update formula)
    
    """
    from datasets import load_dataset as hf_load_dataset
    
    layer_name = handler._layer_name_template.format(handler._layer)
    module = handler._get_module(layer_name)
    hidden_dim = handler.emb_shape
    
    # Get model's max context length
    max_length = getattr(handler.model.config, 'n_positions', 
                        getattr(handler.model.config, 'max_position_embeddings', 1024))
    
    # Accumulate covariance directly on GPU instead of storing all k vectors
    C = torch.zeros(hidden_dim, hidden_dim, dtype=torch.float32, device=handler.device)
    total_tokens = [0]  # Use list to allow modification in hook
    
    def hook(mod, inp, out):
        k = inp[0].detach().float() if isinstance(inp, tuple) else inp.detach().float()
        if len(k.shape) == 3:
            k = k.view(-1, k.shape[-1])  # [batch*seq, hidden]
        if k.shape[1] == hidden_dim:
            # Keep on GPU and accumulate covariance incrementally
            k_gpu = k.to(handler.device)
            C.add_(k_gpu.T @ k_gpu)
            total_tokens[0] += k_gpu.shape[0]
            del k_gpu
    
    handle = module.register_forward_hook(hook)
    
    n_samples = N_rounds * N_k if N_rounds and N_k else 5000
    batch_size = 8  # Process multiple texts at once
    
    print(f"Starting covariance computation: {n_samples} samples, batch_size={batch_size}, max_length={max_length}", flush=True)
    ds = hf_load_dataset("wikitext", "wikitext-103-raw-v1", split="train", streaming=True)
    print("Dataset stream opened", flush=True)
    
    handler.model.eval()
    processed = 0
    batch_texts = []
    
    with torch.no_grad():
        for sample in tqdm(ds, total=n_samples, desc="Computing covariance", mininterval=1.0):
            if processed >= n_samples:
                break
            
            text = sample.get("text", "")
            if len(text.strip()) < 50:
                continue
            
            batch_texts.append(text)
            
            # Process when batch is full
            if len(batch_texts) >= batch_size:
                try:
                    tokens = handler.tokenizer(
                        batch_texts, 
                        return_tensors='pt', 
                        truncation=True, 
                        max_length=max_length,
                        padding=True
                    )
                    handler.model(tokens.input_ids.to(handler.device), 
                                  attention_mask=tokens.attention_mask.to(handler.device))
                    processed += len(batch_texts)
                except Exception as e:
                    pass  # Skip failed batches
                batch_texts = []
                # Clear GPU cache periodically
                torch.cuda.empty_cache()
        
        # Process remaining texts
        if batch_texts and processed < n_samples:
            try:
                tokens = handler.tokenizer(
                    batch_texts, 
                    return_tensors='pt', 
                    truncation=True, 
                    max_length=max_length,
                    padding=True
                )
                handler.model(tokens.input_ids.to(handler.device),
                              attention_mask=tokens.attention_mask.to(handler.device))
                processed += len(batch_texts)
            except:
                pass
    
    handle.remove()
    
    if total_tokens[0] == 0:
        raise ValueError("No samples processed for covariance!")
    
    print(f"Processed {total_tokens[0]} tokens, computing inverse covariance...", flush=True)
    
    # Normalize and add regularization
    cov = C / total_tokens[0]
    cov += 1e-5 * torch.eye(hidden_dim, device=handler.device)
    
    print(f"Inverting {hidden_dim}x{hidden_dim} covariance matrix...", flush=True)
    return torch.linalg.inv(cov)

def second_moment_random(handler, N_rounds, N_k):
    K_list = []
    K = torch.zeros((1, handler.emb_shape))
    K = handler.device_manager.safe_to_device(K)
    while (K == 0).any():
        for _ in tqdm(range(N_rounds)):
            K_list.append(gather_k(handler, fact_tuple=("", "", ""), N = N_k, prefix_range=(2, 20)).detach())
            handler.device_manager.clear_cache()

        K = torch.stack(K_list, dim=1).mean(dim=1).unsqueeze(0)
        K = handler.device_manager.safe_to_device(K).to(torch.float32)
        if (K == 0).any():
            LOGGER.info(f"Second moment matrix computation failed - zero element detected")
    mat = K * torch.transpose(K, 0, 1)
    return mat / mat.norm()

def compute_second_moment(handler, N_rounds: int = 100, N_k: int = 1000, method: SM_Method = SM_Method.WIKIPEDIA):
    """
    Compute the second moment statistics for input of certain mlp layer
    """
    if method == SM_Method.RANDOM:
        # Attempt to estimate the covariance matrix by random prompt sampling
        # Iterative approach due to cuda memory limitations
        return second_moment_random(handler, N_rounds, N_k), N_rounds*N_k, method
    elif method == SM_Method.WIKIPEDIA:
        return second_moment_wikipedia(handler, N_rounds, N_k), N_rounds*N_k, method
    else:
        raise NotImplementedError

def get_second_moment(handler) -> torch.Tensor:
    """
    Returns the appropriate second moment statistics
    """
    # Check the existence of matrix
    if handler.second_moment_path:
        file_paths = [handler.second_moment_path]
    else:
        # Check for both .pt and .npz files
        file_paths = list(Path(handler.second_moment_dir).glob(f"{handler.cfg.model.name.replace('/', '_')}_{handler._layer}_*_*.pt"))
        file_paths += list(Path(handler.second_moment_dir).glob(f"{handler.cfg.model.name.replace('/', '_')}_{handler._layer}_*_*.npz"))

    if len(file_paths):
        LOGGER.info(f"Auto-detected precached second moments: {file_paths}")
        LOGGER.info(f"{file_paths[0]} selected")
        try:
            if file_paths[0].split(".")[-1] == "npz":
                matrix = torch.tensor(np.load(file_paths[0])["mom2.mom2"]).inverse() # IMPORTANT: the originial matrix is not inverted.
            else:
                matrix = torch.load(file_paths[0])
            
            matrix = handler.device_manager.safe_to_device(matrix).to(torch.float32)
            return matrix
        except Exception as e:
            LOGGER.error(f"Failed to load second moment matrix: {e}")
            raise e
    else:
        LOGGER.info(f"Precached second moments not found")
        LOGGER.info(f"Computing second moment statistics for model {handler.cfg.model.name} Module {handler._layer_name_template.format(handler._layer)}")
        inv_cov, count, method = compute_second_moment(handler, method=SM_Method.WIKIPEDIA)
        
        # Ensure directory exists
        save_dir = Path(handler.second_moment_dir)
        save_dir.mkdir(parents=True, exist_ok=True)
        
        save_path = save_dir / f"{handler.cfg.model.name.replace('/', '_')}_{handler._layer}_{method}_{count}.pt"
        torch.save(inv_cov, save_path)
        LOGGER.info(f"Saved second moment to {save_path}")
        return inv_cov
