# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

defaults:
  - /structural@_global_.structural: default
  - /dataset_facts@_global_.dataset_facts: counterfact
  - _self_

name: structural-validate-cov
