# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

svdvals_cache_maxsize: 4096
svdtopk_cache_maxsize: 1024
svdfull_cache_maxsize: 32
