name: "tiiuae/falcon-7b"
models_dir: "../models"
second_moment_dir: "./second_moment_stats"
new_weights_dir: "./new_weights"
device: "cuda"
save_to_local: True
layer_name_template: "transformer.h.{}.mlp.dense_4h_to_h"
fc_layer_name_template: "transformer.h.{}.mlp.dense_h_to_4h"
restore_layer_name_template: "transformer.h.{}"
corrupt_layer_name_template: "transformer.word_embeddings"
layer: 3
second_moment_path: "./second_moment_stats/tiiuae_falcon-7b_3_SM_Method.WIKIPEDIA_100000.pt"
corruption_noise_multiplier: 0.1
lr: 0.5
kl_factor: 0.0625
weight_decay: 0.5
epochs: 10
epsilon: 0.0
dtype: "bf16"
prefix_mode: "self"