name: "EleutherAI/gpt-j-6B"
models_dir: "../models"
save_new_weights: False
new_weights_dir: "./data/new_weights"
second_moment_dir: "./second_moment_stats"
second_moment_path: "./second_moment_stats/EleutherAI_gpt-j-6B_5_SM_Method.WIKIPEDIA_100000.pt"
device: "cuda"
save_to_local: True
layer_name_template: "transformer.h.{}.mlp.fc_out"
fc_layer_name_template: "transformer.h.{}.mlp.fc_in"
restore_layer_name_template: "transformer.h.{}"
corrupt_layer_name_template: "transformer.wte"
layer: 5
corruption_noise_multiplier: 0.115447998046875
lr: 0.5
kl_factor: 0.0625
weight_decay: 0.5
epochs: 20
k_N: 50
v_N: 50
prefix_range: [2, 10]
epsilon: 0.0
dtype: "bf16"
prefix_mode: "self"
