# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

name: "gpt2-large"
second_moment_path: "./data/second_moment_stats/gpt2-large_12_SM_Method.WIKIPEDIA_100000.pt"
layer_name_template: "transformer.h.{}.mlp.c_proj"
fc_layer_name_template: "transformer.h.{}.mlp.c_fc"
restore_layer_name_template: "transformer.h.{}"
corrupt_layer_name_template: "transformer.wte"
layer: 12
corruption_noise_multiplier: 0.1380615234375
dtype: "bf16"
