name: "gpt2-medium"
models_dir: "../models"
second_moment_dir: "./second_moment_stats"
new_weights_dir: "./new_weights"
device: "cuda"
cuda_mode: "soft" 
save_to_local: True # Keep this True until you specifically do not want the model cached locally
layer_name_template: "transformer.h.{}.mlp.c_proj"
restore_layer_name_template: "transformer.h.{}"
corrupt_layer_name_template: "transformer.wte"
layer: 8
corruption_noise_multiplier: 0.2874755859375
lr: 0.5
kl_factor: 0.00625
weight_decay: 0.5
epochs: 20
epsilon: 0.0


prefix_mode: "self"
