name: "gpt2-large"
models_dir: "../models"
second_moment_dir: "./data/second_moment_stats"
second_moment_path: "./data/second_moment_stats/transformer.h.12.mlp.c_proj_float32_mom2_100000.npz"
new_weights_dir: "./data/new_weights"
device: "cuda"
save_to_local: True # Keep this True until you specifically do not want the model cached locally
layer_name_template: "transformer.h.{}.mlp.c_proj"
restore_layer_name_template: "transformer.h.{}"
corrupt_layer_name_template: "transformer.wte"
layer: 12
corruption_noise_multiplier: 0.1380615234375
lr: 0.5
kl_factor: 0.0625
weight_decay: 0.5
epochs: 20
epsilon: 0.0
optimize_pcs: False
dtype: "bf16"
