# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

name: "gpt2-medium"
second_moment_path: "./data/second_moment_stats/gpt2-medium_8_SM_Method.WIKIPEDIA_100000.pt"
cuda_mode: "soft" 
layer_name_template: "transformer.h.{}.mlp.c_proj"
restore_layer_name_template: "transformer.h.{}"
corrupt_layer_name_template: "transformer.wte"
layer: 8
corruption_noise_multiplier: 0.2874755859375
kl_factor: 0.00625
