# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

name: "ibm-granite/granite-4.0-micro"
layer_name_template: "model.layers.{}.shared_mlp.output_linear"
corrupt_layer_name_template: "model.embed_tokens"
restore_layer_name_template: "model.layers.{}"
layer: 9
corruption_noise_multiplier: 1.0
lr: 0.10
epochs: 25
second_moment_path: "data/second_moment_stats/ibm-granite_granite-4.0-micro_9_SM_Method.WIKIPEDIA_100000.pt"

prefix_enforce_latin: True
prefix_min_words: 2
delta_scale: 1.0
