# :copyright: 2025 Jakub Res
# :license: MIT
# :author: Matej Olexa <olexa.matej@gmail.com>
# :author: Jakub Res <iresj@fit.vut.cz>

name: "facebook/opt-6.7b"
layer_name_template: "model.decoder.layers.{}.fc2"
fc_layer_name_template: "model.decoder.layers.{}.fc1"
restore_layer_name_template: "model.decoder.layers.{}"
corrupt_layer_name_template: "model.decoder.embed_tokens"
layer: 14
second_moment_path: "./data/second_moment_stats/facebook_opt-6.7b_14_SM_Method.WIKIPEDIA_100000.pt"
corruption_noise_multiplier: 0.1
epochs: 10
dtype: "bf16"
