name: "facebook/opt-6.7b"
models_dir: "../models"
second_moment_dir: "./second_moment_stats"
new_weights_dir: "./new_weights"
device: "cuda"
save_to_local: True
layer_name_template: "model.decoder.layers.{}.fc2"
fc_layer_name_template: "model.decoder.layers.{}.fc1"
restore_layer_name_template: "model.decoder.layers.{}"
corrupt_layer_name_template: "model.decoder.embed_tokens"
layer: 15
second_moment_path: "./second_moment_stats/facebook_opt-6.7b_15_SM_Method.WIKIPEDIA_20000.pt"
corruption_noise_multiplier: 0.1
lr: 0.5
kl_factor: 0.0625
weight_decay: 0.5
epochs: 10
epsilon: 0.0
dtype: "bf16"
prefix_mode: "self"