name: "Qwen/Qwen2.5-Math-1.5B"
models_dir: "../models"
second_moment_dir: "./second_moment_stats"
new_weights_dir: "./new_weights"
device: "cuda"
save_to_local: True # Keep this True until you specifically do not want the model cached locally
layer_name_template: "model.layers.{}.mlp.down_proj"
restore_layer_name_template: "model.layers.{}"
corrupt_layer_name_template: "model.embed_tokens"
layer: 7
corruption_noise_multiplier: 0.101806640625
lr: 0.05
kl_factor: 0.0625
weight_decay: 0.5
epochs: 20
k_N: 50
v_N: 50
prefix_range: [2, 10]
epsilon: 0.0
prefix_mode: "self"
