name: "Qwen/Qwen3-8B"
models_dir: "../models"
second_moment_dir: "./second_moment_stats"
second_moment_path: "./second_moment_stats/Qwen_Qwen3-8B_10_SM_Method.WIKIPEDIA_100000.pt"
new_weights_dir: "./new_weights"
device: "cuda"
save_to_local: True
layer_name_template: "model.layers.{}.mlp.down_proj"
fc_layer_name_template: "model.layers.{}.mlp.up_proj"
restore_layer_name_template: "model.layers.{}"
corrupt_layer_name_template: "model.embed_tokens"
layer: 10
corruption_noise_multiplier: 0.0777740478515625
lr: 0.5
kl_factor: 0.0625
weight_decay: 0.5
epochs: 20
k_N: 50
v_N: 50
prefix_range: [8, 20]
epsilon: 0.0
optimize_pcs: False
dtype: "bf16"
prefix_mode: "self"
